// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v6.33.2
// source: proto/notification.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export interface SendPaymentNotificationRequest {
  to: string;
  orderId: string;
}

export interface SendPaymentNotificationResponse {
  from: string;
  to: string;
  subject: string;
  content: string;
  notificationStatus: string;
}

export const PAYMENT_PACKAGE_NAME = "payment";

export interface NotificationClient {
  sendPaymentNotification(
    request: SendPaymentNotificationRequest,
    metadata?: Metadata,
  ): Observable<SendPaymentNotificationResponse>;
}

export interface NotificationController {
  sendPaymentNotification(
    request: SendPaymentNotificationRequest,
    metadata?: Metadata,
  ):
    | Promise<SendPaymentNotificationResponse>
    | Observable<SendPaymentNotificationResponse>
    | SendPaymentNotificationResponse;
}

export function NotificationControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendPaymentNotification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Notification", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Notification", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "Notification";
